-- CREATE TABLE marius.COUNTRIES(name VARCHAR2(10));
-- INSERT INTO marius.COUNTRIES (name) VALUES ('UKRAINE');
-- INSERT INTO marius.COUNTRIES (name) VALUES ('GB');
-- INSERT INTO marius.COUNTRIES (name) VALUES ('USA');
-- INSERT INTO marius.COUNTRIES (name) VALUES ('BRAZIL');
-- COMMIT;
-- exit;

