# Generated by Django 4.1.5 on 2023-01-26 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=999, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='id_hotel',
            field=models.FloatField(null=True),
        ),
    ]
