# Generated by Django 4.1.5 on 2023-01-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0002_hotel_id_alter_hotel_id_hotel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='id',
        ),
        migrations.AlterField(
            model_name='hotel',
            name='id_hotel',
            field=models.FloatField(blank=True, default=99999, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
