# Generated by Django 4.1.5 ON dw_manager.2023-01-27 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ebooking', '0003_remove_hotel_id_alter_hotel_id_hotel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atribuie',
            name='id_camera',
            field=models.OneToOneField(db_column='id_camera', on_delete=django.db.models.deletion.DO_NOTHING, to='ebooking.camera'),
        ),
        migrations.AlterField(
            model_name='camera',
            name='id_camera',
            field=models.FloatField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rezervare',
            name='id_rezervare',
            field=models.FloatField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='utilizator',
            name='id_utilizator',
            field=models.FloatField(blank=True, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='zona',
            name='id_zona',
            field=models.FloatField(blank=True, primary_key=True, serialize=False),
        ),
    ]
